spring:
  application:
    name: vendor_main

  datasource:
    url: jdbc:mariadb://localhost:3306/test_database
    username: root
    password: paskaroot
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081